### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by JAHTKELD** [kmwebnet/ECC608-AzureDPS-Provision#1]
Hello. 

I am trying to compile the project but it gives me errors that files are missing

Compiling .pio\build\esp32dev\src\port\hal_esp32_i2c.o
src\port\agenttime_esp.c:19:36: fatal error: ../lwip/apps/sntp/sntp.h: No such file or directory
compilation terminated.
*** [.pio\build\esp32dev\src\port\agenttime_esp.o] Error 1

What is the problem?
Thansk
José

**Comment by JAHTKELD** [comment]
I have fix the problem.

At the agenttime_esp.c file you need to change.
#include "../lwip/apps/sntp/sntp.h"
for  #include "../lwip/lwip/src/include/lwip/apps/sntp.h"

It works. 
Thanks

**Comment by cyberomusubi** [comment]
thank you.
I corrected the include path.
