### ISSUE TITLE
Ssl certificate error with provisioning system usign ECC608 chip signed by atmel usb signer

### ISSUE THREAD

**Issue by correderadiego** [kmwebnet/ECC608-AzureDPS-Provision#6]
Hello 
I am testing your library and it works like a charm. I managed to connect to Azure using your library and Openssl.

The problems appears with the use of an Atmel USB signer. If you use this USB device to make the ECC608 provisioning the device doesn't connect to Azure.
I have attached the complete log. If you look at the end of the file you could see that there is a point where the Azure server closes the connection. 
Do you know any way to debug this error? There is no error or any code from the Azure server.

I know that this is not directly connected with your library however I would appreciate some help.
Thanks for your time

framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:2755: => flush output
framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:2774: message length: 45, out_left: 45
framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:2779: ssl->f_send() returned 45 (-0xffffffd3)
framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:2807: <= flush output
framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:3476: <= write record
framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:3320: <= write handshake message
framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:6507: <= write finished
framework-espidf/components/mbedtls/mbedtls/library/ssl_cli.c:3510: client state: 12
framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:2755: => flush output
framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:2767: <= flush output
framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:5902: => parse change cipher spec
framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:4311: => read record
framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:2536: => fetch input
framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:2697: in_left: 0, nb_want: 5
peer close connection!

**Comment by cyberomusubi** [comment]
I'm sorry, but I don't have the Atmel Signer Module, so I don't know the details.

I checked the logs.

To me the "7.4.9. Finished" defined in RFC 5246 seems relevant.

There, the data in the handshake is hashed, and the AES-GCM encrypted data with the master secret is sent to the server.

Since it is closed from the server after that, it is assumed that the value of the premaster secret in client state: 8 is different from that of the server.

The premaster secret is shared on Diffie-Hellman key exchange,
ATECC608A interrupts this MbedTLS routine to provide the DH key from its private key.

This corresponds to the mbedtls_ecdh_compute_shared function of atca_mbedtls_ecdh.c.

Here, it is set to use the atcab_ecdh_tempkey_ioenc function of ATECC608A.

This creates a key pair in a different area from the slot area called tempkey and set it in a different slot.
The DH key is output while the I2C key interception is prevented by using the IO protection key.

In order to use this feature, you need the proper configuration to use the IO protection key.

Your config doesn't seem to be set properly.

In my config, the 90th to 91st bytes are 06 40.
Microchip support is needed for more details, but why not try changing here?

Or, in the config, set the slot correctly so that ECDH can be handled in a specific slot,
in tlsio_mbedtls.c,

int atca_mbedtls_ecdh_slot_cb(void)
{
    return 0xFFFF;
}

I think you can deal with it by changing the slot number set to 0xFFFF above.

**Comment by correderadiego** [comment]
Thanks for your answer,

 I found some information here but I can not understand it.
http://ww1.microchip.com/downloads/en/DeviceDoc/ATECC608A-TFLXTLS-CryptoAuthentication-Data-Sheet-DS40002138A.pdf
Could be this useful to you?

Thanks again :)

**Comment by cyberomusubi** [comment]
For now, I think the cause is that the ATECC608A has a different configuration.
Does atmel usb signer also configure ATECC608A?

Looking at the presented document, atcab_ecdh_tempkey_ioenc function can be used without problems by specifying the slot number of the IO protection key in the 90th to 91th bytes, and making slotconfig and Keyconfig of that slot read-protected and plaintext write-enabled. You should be able to.

Or is it possible to printf debug how it branches below in src/port/atca_mbedtls_ecdh.c?

>         if (ATECC608A == atcab_get_device()->mIface->mIfaceCFG->devtype)
>         {
>             ret = atca_mbedtls_ecdh_ioprot_cb(secret);
>             if (!ret)
>             {
>                 if (slotid > 15)
>                 {
>                     ret = atcab_ecdh_tempkey_ioenc(public_key, shared_key, secret);
>                 }
>                 else
>                 {
>                     ret = atcab_ecdh_ioenc(slotid, public_key, shared_key, secret);
>                 }
>             }
>             mbedtls_platform_zeroize(secret, ATCA_KEY_SIZE);
>         }
>         else
>         {
>             ret = atcab_ecdh(slotid, public_key, shared_key);
>         }

I'm sorry if it's irrelevant.

**Comment by correderadiego** [comment]
Hello,
Thanks for all your time. I have manage to progress a little bit. There is a point with the USB signer where I could introduce your ATECC608A register configuration.
The problem has evolved and the logs has changed a little. I have adde a little part of the log for you to check if you have some time. Thanks again.

The fact is that I have some different configuration in the certificate itself. In your certificate I can see the device Id in the CN of the device certificate. Meanwhile my certificate has a fixed name iConnectDevice. What do you use this id for?? Is this number necessary for the provisioning system?

I attached the certificates references an some logs. Thanks again.

home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:5381: issuer name       : O=IConnectKELD, CN=KELD
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:5381: subject name      : O=IConnectCaldera, CN=0123800db73ac5a1ee
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:5381: issued  on        : 2020-05-29 12:00:00
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:5381: expires on        : 3000-12-31 23:59:59
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:5381: signed using      : ECDSA with SHA256
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:5381: EC key size       : 256 bits


/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:5381: issuer name       : O=DOMUSA_TEKNIK, CN=iConnectSigner2 0002
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:5381: subject name      : O=DOMUSA_TEKNIK, CN=iConnectDevice
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:5381: issued  on        : 2020-06-08 16:00:00
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:5381: expires on        : 9999-12-31 23:59:59
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:5381: signed using      : ECDSA with SHA256
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:5381: EC key size       : 256 bits



me//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_cli.c:3510: client state: 15
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:2755: => flush output
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:2767: <= flush output
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:6336: => handshake wrapup
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:6309: => handshake wrapup: final free
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:6329: <= handshake wrapup: final free
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:6391: <= handshake wrapup
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:8094: <= handshake
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:8682: => write
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:3343: => write record
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:1445: => encrypt buf
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:1456: dumping 'before encrypt: output payload' (131 bytes)
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:1456: 0000:  10 80 01 00 04 4d 51 54 54 04 82 00 00 00 12 30  .....MQTT......0
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:1456: 0010:  31 32 33 65 39 64 32 32 39 61 31 30 63 65 34 65  123e9d229a10ce4e
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:1456: 0020:  65 00 60 30 6e 65 30 30 30 43 41 44 34 31 2f 72  e.`0ne000CAD41/r
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:1456: 0030:  65 67 69 73 74 72 61 74 69 6f 6e 73 2f 30 31 32  egistrations/012
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:1456: 0040:  33 65 39 64 32 32 39 61 31 30 63 65 34 65 65 2f  3e9d229a10ce4ee/
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:1456: 0050:  61 70 69 2d 76 65 72 73 69 6f 6e 3d 32 30 31 38  api-version=2018
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:1456: 0060:  2d 30 39 2d 30 31 2d 70 72 65 76 69 65 77 26 43  -09-01-preview&C
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:1456: 0070:  6c 69 65 6e 74 56 65 72 73 69 6f 6e 3d 31 2e 32  lientVersion=1.2
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:1456: 0080:  2e 31 34                                         .14
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:1574: dumping 'additional data for AEAD' (13 bytes)
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:1574: 0000:  00 00 00 00 00 00 00 01 17 03 03 00 83           .............
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:1605: dumping 'IV used (internal)' (12 bytes)
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:1605: 0000:  ee 0a e6 e7 00 00 00 00 00 00 00 01              ............
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:1607: dumping 'IV used (transmitted)' (8 bytes)
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:1607: 0000:  00 00 00 00 00 00 00 01                          ........
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:1618: before encrypt: msglen = 139, including 0 bytes of padding
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:1643: dumping 'after encrypt: tag' (16 bytes)
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:1643: 0000:  8c d8 e2 c0 23 a8 36 8f e4 1d b9 59 6c 42 fd 3c  ....#.6....YlB.<
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:1781: <= encrypt buf
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:3423: output record: msgtype = 23, version = [3:3], msglen = 155
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:3426: dumping 'output record sent to network' (160 bytes)
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:3426: 0000:  17 03 03 00 9b 00 00 00 00 00 00 00 01 28 0b f4  .............(..
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:3426: 0010:  06 f4 03 e0 5d a1 53 ca fa 97 b1 11 77 c4 f6 a8  ....].S.....w...
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:3426: 0020:  c4 6d 93 db a3 a2 be f3 02 09 c7 e2 4a b4 f3 3b  .m..........J..;
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:3426: 0030:  02 ae e0 b4 3f e4 43 fa 3a 52 bf 4f 87 9c 2d 3e  ....?.C.:R.O..->
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:3426: 0040:  c6 90 9a 74 85 ce ce 1c 51 1c d6 fe 4b 81 f3 79  ...t....Q...K..y
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:3426: 0050:  45 c0 81 73 99 f2 0e b3 ef 8a 87 d6 31 af f2 9b  E..s........1...
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:3426: 0060:  a9 a8 5a ef 15 78 27 15 1f bd ca f3 e6 24 eb 14  ..Z..x'......$..
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:3426: 0070:  5a 79 26 eb 14 88 7a 29 03 c8 c7 d8 9f be cc 62  Zy&...z).......b
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:3426: 0080:  b7 4e 8c d2 96 6b 61 ef b8 50 49 a5 16 4a 03 9b  .N...ka..PI..J..
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:3426: 0090:  8c d8 e2 c0 23 a8 36 8f e4 1d b9 59 6c 42 fd 3c  ....#.6....YlB.<
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:2755: => flush output
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:2774: message length: 160, out_left: 160
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:2779: ssl->f_send() returned 160 (-0xffffff60)
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:2807: <= flush output
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:3476: <= write record
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:8710: <= write
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:8270: => read
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:4311: => read record
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:2536: => fetch input
/home//.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/ssl_tls.c:2697: in_left: 0, nb_want: 5
<== recv data heap:161068, recvlen:33
on_underlying_io_bytes_received count:33
peer close connection!
Error: Time:Tue Jun  9 10:00:57 2020 File:lib/esp-azure/azure-iot-sdk-c/provisioning_client/src/prov_transport_mqtt_common.c Func:mqtt_error_callback Line:136 MQTT communication error

**Comment by cyberomusubi** [comment]
The problem may be that the common name of the device is duplicated or registered.
I intended to make a template that could be applied across multiple devices, but I'll check again.

**Comment by correderadiego** [comment]
I have a question about the scripts used to generate the cert_chain.c file. I have realized that the Usb signer creates its own configuration file. However I can see that there is a difference in the end part of the g_cert_def_1_signer :
- This is your configuration
  .cert_elements          = g_cert_elements_1_signer,
    .cert_elements_count    = sizeof(g_cert_elements_1_signer) / sizeof(g_cert_elements_1_signer[0]),
- This is the configuration of the usb signer:
  .cert_elements          =NULL,
    .cert_elements_count    = 0,
Could you explain me the difference between both of them? I can't see the reason of this difference or If this could be important for the connection

Thanks again and sorry for all the inconveniences

**Comment by cyberomusubi** [comment]
By the way, if you're thinking about provisioning to multiple devices, see also below.
I Upload [ECC608-MassProvosioning](https://github.com/kmwebnet/ECC608-MassProvosioning).
could you try it?

**Comment by cyberomusubi** [comment]
The value will be referenced by the following function used when reconstructing the certificate.

https://microchiptech.github.io/cryptoauthlib/a01992.html#gace8ac017f58840c296fe2cf29bdaa2fe


int atcacert_cert_build_start 	( 	atcacert_build_state_t *  	build_state,
		const atcacert_def_t *  	cert_def,
		uint8_t *  	cert,
		size_t *  	cert_size,
		const uint8_t  	ca_public_key[64] 
	) 	


[in]	ca_public_key	ECC P256 public key of the certificate authority (issuer) for 
the certificate being built. Set to NULL if the authority key id is not needed, set 
properly in the cert_def template, or stored on the device as specified in the 
cert_def cert_elements.

I don't know the relationship to your trouble, but I think you have a certificate that does not include that item.

The point to be worried about is that the effective year is 9999.

**Comment by cyberomusubi** [comment]
When I tried connecting to Azure IoT again, after the TLS handshake was completed, 
I was disconnected after sending the following in the same way.


ssl_tls.c:1456: 0000:  10 5e 00 04 4d 51 54 54 04 82 00 78 00 01 33 00  .^..MQTT...x..3.
ssl_tls.c:1456: 0010:  4f 6b 6d 77 65 62 61 7a 75 72 65 69 6f 74 74 65  Okmwebazureiotte
ssl_tls.c:1456: 0020:  73 74 32 2e 61 7a 75 72 65 2d 64 65 76 69 63 65  st2.azure-device
ssl_tls.c:1456: 0030:  73 2e 6e 65 74 2f 30 31 32 33 33 36 30 63 64 62  s.net/0123360cdb
ssl_tls.c:1456: 0040:  32 66 36 66 62 35 65 65 2f 3f 61 70 69 2d 76 65  2f6fb5ee/?api-ve
ssl_tls.c:1456: 0050:  72 73 69 6f 6e 3d 32 30 31 38 2d 30 36 2d 33 30  rsion=2018-06-30


As a result of various investigations, I was able to connect by setting the following.

![image](https://user-images.githubusercontent.com/46954791/84485072-95893f00-acd6-11ea-8715-771500fc5aec.png)
![image](https://user-images.githubusercontent.com/46954791/84485159-b2257700-acd6-11ea-9c68-da45112e724b.png)

**Comment by correderadiego** [comment]
Thanks for your reply. 
I have already configure the options that you define in your previous message. The system continues disconnecting with this configuration enabled.

I am comparing the certificates generated by both devices and I found a difference with one of the fields of the certificate. Openssl marks this field with the label critical but the Usb device doesn't.

  X509v3 Basic Constraints: critical
                CA:TRUE

I have opened one technical question with microchip to solve this problem.

**Comment by correderadiego** [comment]
> By the way, if you're thinking about provisioning to multiple devices, see also below.
> I Upload [ECC608-MassProvosioning](https://github.com/kmwebnet/ECC608-MassProvosioning).
> could you try it?

I will try it as soon as I have a moment. This code looks promising and will solve my problems. Thanks for your time.

**Comment by correderadiego** [comment]
Hello,

First of all I would like to apologize for my late reply. I have got some time to test your code and It works very well. Thanks for your effort.
