### ISSUE TITLE
Port to ESP_IDF 4.0 (1.12.4 in Platformio)

### ISSUE THREAD

**Issue by JAHTKELD** [kmwebnet/ECC608-AzureDPS-Provision#7]
Hello:
Thanks for massproducction firmware , it works very well and it is very useful.

I am using the newest platformio and ESP_IDF (4.0, , platformio1.12.4), and I have managed to get the massproduction firmware to work, placing the cryptoautholin library in the "lib" directory and adding the necessary CmakeList.txt files

Now trying it with AzureDPS I have many errors like

src \ iothubtransport_mqtt_common.c: In function 'retrieve_device_method_rid_info':
src \ iothubtransport_mqtt_common.c: 420: 28: error: implicit declaration of function 'STRING_new'; did you mean 'STRINGS_H'? [-Werror = implicit-function-declaration]

and 85 problems like

"resource": "/c:/Users/JOSE/Documents/PlatformIO/Projects/ECC608-AzureDPS-Provision/lib/esp-azure/azure-iot-sdk-c/c-utility/inc/azure_c_shared_utility/strings.h "
"owner": "cpp",
"severity": 8,
"message": "unknown type name 'IF'",
"startLineNumber": 18,
"startColumn": 1,
"endLineNumber": 18,
"endColumn": 1

{
"resource": "/c:/Users/JOSE/Documents/PlatformIO/Projects/ECC608-AzureDPS-Provision/src/iothubtransport_mqtt_common.c",
"owner": "cpp",
"severity": 8,
"message": "implicit declaration of function 'STRING_delete'; did you mean 'BUFFER_delete'? [-Werror = implicit-function-declaration]",
"startLineNumber": 319,
"startColumn": 5,
"endLineNumber": 319,
"endColumn": 5
}

{
"resource": "/c:/Users/JOSE/Documents/PlatformIO/Projects/ECC608-AzureDPS-Provision/.vscode/c_cpp_properties.json",
"owner": "c: \\ Users \\ JOSE \\ Documents \\ PlatformIO \\ Projects \\ ECC608-AzureDPS-Provision",
"severity": 4,
"message": "cant find \" C: \\ Users \\ JOSE \\. platformio \\ packages \\ framework-espidf@3.30300.190916 \\ components \\ expat \\ expat \\ lib \ ".",
"startLineNumber": 78,
"startColumn": 17,
"endLineNumber": 78,
"endColumn": 112
}

Which is better to continue with EDP_IDF 3.2 (platformio 1.11 .4) or keep trying to advance to ESP_IDF 4.0? I think this is almost beyond my knowledge

**Comment by JAHTKELD** [comment]
I'm going to try to do it with this example, add Azure-iot as a component

https://github.com/dycodex/esp32-azure-iot-training/tree/master/day3/finished/esp32_azure_iot_hub

**Comment by JAHTKELD** [comment]
I give up, too complicated for me to create the Cmakelist.txt and component.mk for the Esp-Azure component

**-- Configuring incomplete, errors occurred!
See also "C:/Users/JOSE/Documents/PlatformIO/Projects/esp32_azure_iot_hub/.pio/build/esp-wrover-kit/CMakeFiles/CMakeOutput.log".

fatal: not a git repository (or any of the parent directories): .git
CMake Error at C:/Users/JOSE/.platformio/packages/framework-espidf/tools/cmake/component.cmake:222 (message):
  CMake Warning (dev) at components/esp-azure/CMakeLists.txt:38:**

**Comment by cyberomusubi** [comment]
I am trying to rebuild with esp-idf 4.0.1 and cryptoauthlib 3.2.
It seems that it will take time because the HAL is destroyed.
Regarding provisioning to Azure DPS, I think that there is another method, as it only sends fixed MQTT messages in order.

**Comment by cyberomusubi** [comment]
I update version of AzureDPS-Provision.
could you try it?
[ECC608-AzureDPS-Provision-idf4](https://github.com/kmwebnet/ECC608-AzureDPS-Provision-idf4)
note that it has chenged I2C port and GPIO pins.

**Comment by JAHTKELD** [comment]
Thanks, I will try it this weekend. I have found some problem with MassProvisioning, sometimes it returns that it cannot write the device certificate (error 4), and after several attempts uploading the program and executing the script the given one is correct. I don't think it has to do but I use the 16MB ESP32 with a 2 OTA partition of its own

**Comment by JAHTKELD** [comment]
it works. I get

Provisioning Status: PROV_DEVICE_REG_STATUS_CONNECTED
Provisioning Status: PROV_DEVICE_REG_STATUS_ASSIGNING
Registration Information received from service: XXXIoTHub.azure-devices.net!
Creating IoTHub Device handle
Sending 1 messages to IoTHub every 2 seconds for 2 messages (Send any message to stop)
IoTHubClient_LL_SendEventAsync accepted message [1] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [2] for transmission to IoT Hub.

Thanks
